[[systems]]
# system1
  [systems.1.lane1]
     tty = "tty1"
     BaudRate = 250000
     StartPosLeft = true
     EnableTankPos = [1, 3, 5]
     [systems.1.lane1.distance]
       standard = 600
       tank2to3 = 800
  [systems.1.lane2]
     tty = "tty2"
     baudrate = 250000
     StartPosLeft = true
     EnableTankPos = [1, 3, 5]
     [systems.1.lane2.distance]
       standard = 600

# system2
  [systems.2.lane1]
     tty = "tty10"
     BaudRate = 250000
     StartPosLeft = true
     EnableTankPos = [1, 3, 5]
     [systems.2.lane1.distance]
       standard = 600